Bond Source Prototype
abarret/clotting_model pull request #23
Opened 2022-02-25 18:53 UTC by jmcragun

This is my attempt at implementing `IBTK::CartGridFunction` for bond source terms. I interpreted this as computing alpha as given in the new model (equations 8-10) it is heavily inspired by `ActivatedPlateletSource` and since they use the same cell variables (as far as I can tell, save for a few constants) many functions like `setDataOnPatchHierarchy` are exactly the same. So please let me know if those need to be updated in some nontrivial way.

I have not built this yet so do not merge until I can confirm that it is free of compilations (I'm still not totally sure how to build the project just yet)

2022-02-25 18:54 UTC, jmcragun commented
Actually, it just occurred to me that I need to include these files in the makefile. Will do that in a sec.

2022-02-25 19:23 UTC, abarret requested changes
You should also add BondSource.cpp to the CMakeLists.txt file

2022-02-25 19:23 UTC, abarret commented on BondSource.cpp
> +                    SAMRAI::tbox::Pointer<SAMRAI::hier::Variable<NDIM>> w_var,
Take a look at the modifications I made to the platelet sources for the wall sites. Wall sites are not controlled by the advection diffusion integrator, we have to get them in a different way.
https://github.com/abarret/clotting_model/blob/0251592732b153423aab269b6a2d2159b2d282f1/PlateletSource.h#L89

2022-02-25 19:23 UTC, abarret commented on BondSource.cpp
> +    // Calling this "Alpha data" because I believe the goal for this method is to compute alpha (10)
This should be computing alpha - beta * z

2022-02-25 22:39 UTC, abarret requested changes

2022-02-25 22:39 UTC, abarret commented on BondSource.cpp
> +                    SAMRAI::tbox::Pointer<SAMRAI::hier::Variable<NDIM>> w_var,
We need some way to set `z_var` and `d_sigma_var`. I would suggest setting them in the constructor (in place of `w_var` which is no longer needed).

2022-02-25 22:39 UTC, abarret commented on BondSource.cpp
> +        double beta = 0.0;
Beta is defined in between the dimension checks.
```suggestion
```

2022-03-01 20:10 UTC, abarret requested changes

2022-03-01 20:10 UTC, abarret commented on BondSource.cpp
> +        double phi_u = (*phi_u_data)(idx);
```suggestion
        double phi_a = (*phi_a_data)(idx);
```

2022-03-01 20:10 UTC, abarret commented on BondSource.cpp
> +        (*bond_data)(idx) = alpha - beta * z
```suggestion
        (*bond_data)(idx) = alpha - beta * z;
```

2022-03-01 20:10 UTC, abarret commented on BondSource.h
> +    }
```suggestion
    };
```

2022-03-01 20:12 UTC, abarret commented
I fixed a few compilation things. I think it looks good otherwise. I'll go ahead and merge so we can finish wrapping things up.

2022-03-01 20:13 UTC, merged

2022-03-01 20:50 UTC, jmcragun commented
Thanks! Merging now

2022-03-01 20:50 UTC, jmcragun commented
Thanks!